//------------------------------------------------------------------------------
// <auto-generated>由设置设计器生成。</auto-generated>
//------------------------------------------------------------------------------
namespace WindowsFormsApp1.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("SettingsSingleFileGenerator", "1.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static readonly Settings defaultInstance =
            (Settings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 账号 { get => (string)this["账号"]; set => this["账号"] = value; }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 密码 { get => (string)this["密码"]; set => this["密码"] = value; }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 显示密码的勾取 { get => (bool)this["显示密码的勾取"]; set => this["显示密码的勾取"] = value; }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 保存密码的勾取 { get => (bool)this["保存密码的勾取"]; set => this["保存密码的勾取"] = value; }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 当前料号 { get => (string)this["当前料号"]; set => this["当前料号"] = value; }
    }
}
