//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 账号 {
            get {
                return ((string)(this["账号"]));
            }
            set {
                this["账号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机1深度学习模板\\model_训练-260518-135257_1_opt.hdl")]
        public string 相机1hdl文件路径 {
            get {
                return ((string)(this["相机1hdl文件路径"]));
            }
            set {
                this["相机1hdl文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机1深度学习模板\\model_训练-260518-135257_1_opt_dl_preprocess_params.hdict")]
        public string 相机1hdict文件路径 {
            get {
                return ((string)(this["相机1hdict文件路径"]));
            }
            set {
                this["相机1hdict文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机2深度学习模板\\model_训练-260518-104059_opt.hdl")]
        public string 相机2hdl文件路径 {
            get {
                return ((string)(this["相机2hdl文件路径"]));
            }
            set {
                this["相机2hdl文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机2深度学习模板\\model_训练-260518-104059_opt_dl_preprocess_params.hdict")]
        public string 相机2hdict文件路径 {
            get {
                return ((string)(this["相机2hdict文件路径"]));
            }
            set {
                this["相机2hdict文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1图片保存路径 {
            get {
                return ((string)(this["相机1图片保存路径"]));
            }
            set {
                this["相机1图片保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2图片保存路径 {
            get {
                return ((string)(this["相机2图片保存路径"]));
            }
            set {
                this["相机2图片保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3图片保存路径 {
            get {
                return ((string)(this["相机3图片保存路径"]));
            }
            set {
                this["相机3图片保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机3深度学习模板\\model_训练-260520-113859_opt.hdl")]
        public string 相机3hdl文件路径 {
            get {
                return ((string)(this["相机3hdl文件路径"]));
            }
            set {
                this["相机3hdl文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机3深度学习模板\\model_训练-260520-113859_opt_dl_preprocess_params.hdict")]
        public string 相机3hdict文件路径 {
            get {
                return ((string)(this["相机3hdict文件路径"]));
            }
            set {
                this["相机3hdict文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机1模板数量 {
            get {
                return ((string)(this["相机1模板数量"]));
            }
            set {
                this["相机1模板数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机1对比度 {
            get {
                return ((string)(this["相机1对比度"]));
            }
            set {
                this["相机1对比度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机1匹配度 {
            get {
                return ((string)(this["相机1匹配度"]));
            }
            set {
                this["相机1匹配度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机2模板数量 {
            get {
                return ((string)(this["相机2模板数量"]));
            }
            set {
                this["相机2模板数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机2对比度 {
            get {
                return ((string)(this["相机2对比度"]));
            }
            set {
                this["相机2对比度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机2匹配度 {
            get {
                return ((string)(this["相机2匹配度"]));
            }
            set {
                this["相机2匹配度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机3模板数量 {
            get {
                return ((string)(this["相机3模板数量"]));
            }
            set {
                this["相机3模板数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机3对比度 {
            get {
                return ((string)(this["相机3对比度"]));
            }
            set {
                this["相机3对比度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string 相机3匹配度 {
            get {
                return ((string)(this["相机3匹配度"]));
            }
            set {
                this["相机3匹配度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4图片保存路径 {
            get {
                return ((string)(this["相机4图片保存路径"]));
            }
            set {
                this["相机4图片保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机3深度学习模板\\model_训练-260520-113859_opt.hdl")]
        public string 相机4hdl文件路径 {
            get {
                return ((string)(this["相机4hdl文件路径"]));
            }
            set {
                this["相机4hdl文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("相机3深度学习模板\\model_训练-260520-113859_opt_dl_preprocess_params.hdict")]
        public string 相机4hdict文件路径 {
            get {
                return ((string)(this["相机4hdict文件路径"]));
            }
            set {
                this["相机4hdict文件路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string 权限时间设置 {
            get {
                return ((string)(this["权限时间设置"]));
            }
            set {
                this["权限时间设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string 相机数量设置 {
            get {
                return ((string)(this["相机数量设置"]));
            }
            set {
                this["相机数量设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 图片删除时间 {
            get {
                return ((string)(this["图片删除时间"]));
            }
            set {
                this["图片删除时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4模板数量 {
            get {
                return ((string)(this["相机4模板数量"]));
            }
            set {
                this["相机4模板数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4对比度 {
            get {
                return ((string)(this["相机4对比度"]));
            }
            set {
                this["相机4对比度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4匹配度 {
            get {
                return ((string)(this["相机4匹配度"]));
            }
            set {
                this["相机4匹配度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1总数 {
            get {
                return ((string)(this["相机1总数"]));
            }
            set {
                this["相机1总数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1OK数 {
            get {
                return ((string)(this["相机1OK数"]));
            }
            set {
                this["相机1OK数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1NG数 {
            get {
                return ((string)(this["相机1NG数"]));
            }
            set {
                this["相机1NG数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2总数 {
            get {
                return ((string)(this["相机2总数"]));
            }
            set {
                this["相机2总数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2OK数 {
            get {
                return ((string)(this["相机2OK数"]));
            }
            set {
                this["相机2OK数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2NG数 {
            get {
                return ((string)(this["相机2NG数"]));
            }
            set {
                this["相机2NG数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3总数 {
            get {
                return ((string)(this["相机3总数"]));
            }
            set {
                this["相机3总数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3OK数 {
            get {
                return ((string)(this["相机3OK数"]));
            }
            set {
                this["相机3OK数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3NG数 {
            get {
                return ((string)(this["相机3NG数"]));
            }
            set {
                this["相机3NG数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4总数 {
            get {
                return ((string)(this["相机4总数"]));
            }
            set {
                this["相机4总数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4OK数 {
            get {
                return ((string)(this["相机4OK数"]));
            }
            set {
                this["相机4OK数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4NG数 {
            get {
                return ((string)(this["相机4NG数"]));
            }
            set {
                this["相机4NG数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1OK图保存路径 {
            get {
                return ((string)(this["相机1OK图保存路径"]));
            }
            set {
                this["相机1OK图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1NG图保存路径 {
            get {
                return ((string)(this["相机1NG图保存路径"]));
            }
            set {
                this["相机1NG图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2OK图保存路径 {
            get {
                return ((string)(this["相机2OK图保存路径"]));
            }
            set {
                this["相机2OK图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2NG图保存路径 {
            get {
                return ((string)(this["相机2NG图保存路径"]));
            }
            set {
                this["相机2NG图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3OK图保存路径 {
            get {
                return ((string)(this["相机3OK图保存路径"]));
            }
            set {
                this["相机3OK图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3NG图保存路径 {
            get {
                return ((string)(this["相机3NG图保存路径"]));
            }
            set {
                this["相机3NG图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4OK图保存路径 {
            get {
                return ((string)(this["相机4OK图保存路径"]));
            }
            set {
                this["相机4OK图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4NG图保存路径 {
            get {
                return ((string)(this["相机4NG图保存路径"]));
            }
            set {
                this["相机4NG图保存路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 显示密码的勾取 {
            get {
                return ((bool)(this["显示密码的勾取"]));
            }
            set {
                this["显示密码的勾取"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 保存密码的勾取 {
            get {
                return ((bool)(this["保存密码的勾取"]));
            }
            set {
                this["保存密码的勾取"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 密码 {
            get {
                return ((string)(this["密码"]));
            }
            set {
                this["密码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机1配方地址 {
            get {
                return ((string)(this["相机1配方地址"]));
            }
            set {
                this["相机1配方地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机2配方地址 {
            get {
                return ((string)(this["相机2配方地址"]));
            }
            set {
                this["相机2配方地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机3配方地址 {
            get {
                return ((string)(this["相机3配方地址"]));
            }
            set {
                this["相机3配方地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 相机4配方地址 {
            get {
                return ((string)(this["相机4配方地址"]));
            }
            set {
                this["相机4配方地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 设置 {
            get {
                return ((string)(this["设置"]));
            }
            set {
                this["设置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 当前料号 {
            get {
                return ((string)(this["当前料号"]));
            }
            set {
                this["当前料号"] = value;
            }
        }
    }
}
