namespace WindowsFormsApp1
{
    partial class 料号添加
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this.splitContainer3 = new System.Windows.Forms.SplitContainer();
            this.txt相机1hdl = new System.Windows.Forms.TextBox();
            this.txt相机1hdict = new System.Windows.Forms.TextBox();
            this.txt相机1模板保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机1原图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机1OK图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机1NG图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机2hdl = new System.Windows.Forms.TextBox();
            this.txt相机2hdict = new System.Windows.Forms.TextBox();
            this.txt相机2模板保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机2原图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机2OK图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机2NG图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机3hdl = new System.Windows.Forms.TextBox();
            this.txt相机3hdict = new System.Windows.Forms.TextBox();
            this.txt相机3模板保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机3原图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机3OK图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机3NG图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机4hdl = new System.Windows.Forms.TextBox();
            this.txt相机4hdict = new System.Windows.Forms.TextBox();
            this.txt相机4模板保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机4原图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机4OK图保存路径 = new System.Windows.Forms.TextBox();
            this.txt相机4NG图保存路径 = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label54 = new System.Windows.Forms.Label();
            this.label53 = new System.Windows.Forms.Label();
            this.label52 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label57 = new System.Windows.Forms.Label();
            this.label56 = new System.Windows.Forms.Label();
            this.label55 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label60 = new System.Windows.Forms.Label();
            this.label59 = new System.Windows.Forms.Label();
            this.label58 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.label15 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label63 = new System.Windows.Forms.Label();
            this.label62 = new System.Windows.Forms.Label();
            this.label61 = new System.Windows.Forms.Label();
            this.label39 = new System.Windows.Forms.Label();
            this.label40 = new System.Windows.Forms.Label();
            this.label41 = new System.Windows.Forms.Label();
            this.label42 = new System.Windows.Forms.Label();
            this.txt相机1模板数量 = new System.Windows.Forms.NumericUpDown();
            this.txt相机1对比度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机1匹配度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机1曝光时间 = new System.Windows.Forms.NumericUpDown();
            this.txt相机1增益 = new System.Windows.Forms.NumericUpDown();
            this.txt相机2模板数量 = new System.Windows.Forms.NumericUpDown();
            this.txt相机2对比度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机2匹配度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机2曝光时间 = new System.Windows.Forms.NumericUpDown();
            this.txt相机2增益 = new System.Windows.Forms.NumericUpDown();
            this.txt相机3模板数量 = new System.Windows.Forms.NumericUpDown();
            this.txt相机3对比度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机3匹配度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机3曝光时间 = new System.Windows.Forms.NumericUpDown();
            this.txt相机3增益 = new System.Windows.Forms.NumericUpDown();
            this.txt相机4模板数量 = new System.Windows.Forms.NumericUpDown();
            this.txt相机4对比度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机4匹配度 = new System.Windows.Forms.NumericUpDown();
            this.txt相机4曝光时间 = new System.Windows.Forms.NumericUpDown();
            this.txt相机4增益 = new System.Windows.Forms.NumericUpDown();
            this.label19 = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.label21 = new System.Windows.Forms.Label();
            this.label22 = new System.Windows.Forms.Label();
            this.label23 = new System.Windows.Forms.Label();
            this.label24 = new System.Windows.Forms.Label();
            this.label25 = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.label27 = new System.Windows.Forms.Label();
            this.label28 = new System.Windows.Forms.Label();
            this.label29 = new System.Windows.Forms.Label();
            this.label30 = new System.Windows.Forms.Label();
            this.label31 = new System.Windows.Forms.Label();
            this.label32 = new System.Windows.Forms.Label();
            this.label33 = new System.Windows.Forms.Label();
            this.label34 = new System.Windows.Forms.Label();
            this.label35 = new System.Windows.Forms.Label();
            this.label36 = new System.Windows.Forms.Label();
            this.label37 = new System.Windows.Forms.Label();
            this.label38 = new System.Windows.Forms.Label();
            this.label44 = new System.Windows.Forms.Label();
            this.label45 = new System.Windows.Forms.Label();
            this.label48 = new System.Windows.Forms.Label();
            this.label49 = new System.Windows.Forms.Label();
            this.label46 = new System.Windows.Forms.Label();
            this.label47 = new System.Windows.Forms.Label();
            this.label50 = new System.Windows.Forms.Label();
            this.label51 = new System.Windows.Forms.Label();
            this.txt权限时间 = new System.Windows.Forms.TextBox();
            this.txt图片删除日期 = new System.Windows.Forms.TextBox();
            this.txt相机数量设置 = new System.Windows.Forms.ComboBox();
            this.txt料号名称 = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label17 = new System.Windows.Forms.Label();
            this.label43 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.button11 = new System.Windows.Forms.Button();
            this.button14 = new System.Windows.Forms.Button();
            this.button15 = new System.Windows.Forms.Button();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).BeginInit();
            this.splitContainer3.Panel1.SuspendLayout();
            this.splitContainer3.Panel2.SuspendLayout();
            this.splitContainer3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1模板数量)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1对比度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1匹配度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1曝光时间)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1增益)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2模板数量)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2对比度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2匹配度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2曝光时间)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2增益)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3模板数量)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3对比度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3匹配度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3曝光时间)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3增益)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4模板数量)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4对比度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4匹配度)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4曝光时间)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4增益)).BeginInit();
            this.SuspendLayout();
            // 
            // listBox1
            // 
            this.listBox1.Dock = System.Windows.Forms.DockStyle.Left;
            this.listBox1.Font = new System.Drawing.Font("宋体", 10.5F);
            this.listBox1.ItemHeight = 14;
            this.listBox1.Location = new System.Drawing.Point(0, 0);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(170, 720);
            this.listBox1.TabIndex = 0;
            this.listBox1.SelectedIndexChanged += new System.EventHandler(this.listBox1_SelectedIndexChanged);
            // 
            // panel1
            // 
            this.panel1.AutoScroll = true;
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.txt相机1hdl);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.txt相机1hdict);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.txt相机1模板保存路径);
            this.panel1.Controls.Add(this.label54);
            this.panel1.Controls.Add(this.txt相机1原图保存路径);
            this.panel1.Controls.Add(this.label53);
            this.panel1.Controls.Add(this.txt相机1OK图保存路径);
            this.panel1.Controls.Add(this.label52);
            this.panel1.Controls.Add(this.txt相机1NG图保存路径);
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.txt相机2hdl);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.txt相机2hdict);
            this.panel1.Controls.Add(this.label6);
            this.panel1.Controls.Add(this.txt相机2模板保存路径);
            this.panel1.Controls.Add(this.label57);
            this.panel1.Controls.Add(this.txt相机2原图保存路径);
            this.panel1.Controls.Add(this.label56);
            this.panel1.Controls.Add(this.txt相机2OK图保存路径);
            this.panel1.Controls.Add(this.label55);
            this.panel1.Controls.Add(this.txt相机2NG图保存路径);
            this.panel1.Controls.Add(this.label11);
            this.panel1.Controls.Add(this.txt相机3hdict);
            this.panel1.Controls.Add(this.label12);
            this.panel1.Controls.Add(this.txt相机3hdl);
            this.panel1.Controls.Add(this.label16);
            this.panel1.Controls.Add(this.txt相机3模板保存路径);
            this.panel1.Controls.Add(this.label60);
            this.panel1.Controls.Add(this.txt相机3原图保存路径);
            this.panel1.Controls.Add(this.label59);
            this.panel1.Controls.Add(this.txt相机3OK图保存路径);
            this.panel1.Controls.Add(this.label58);
            this.panel1.Controls.Add(this.txt相机3NG图保存路径);
            this.panel1.Controls.Add(this.label14);
            this.panel1.Controls.Add(this.txt相机4hdict);
            this.panel1.Controls.Add(this.label15);
            this.panel1.Controls.Add(this.txt相机4hdl);
            this.panel1.Controls.Add(this.label13);
            this.panel1.Controls.Add(this.txt相机4模板保存路径);
            this.panel1.Controls.Add(this.label63);
            this.panel1.Controls.Add(this.txt相机4原图保存路径);
            this.panel1.Controls.Add(this.label62);
            this.panel1.Controls.Add(this.txt相机4OK图保存路径);
            this.panel1.Controls.Add(this.label61);
            this.panel1.Controls.Add(this.txt相机4NG图保存路径);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(170, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1110, 235);
            this.panel1.TabIndex = 1;
            // 
            // panel3
            // 
            this.panel3.AutoScroll = true;
            this.panel3.Controls.Add(this.splitContainer1);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel3.Location = new System.Drawing.Point(170, 235);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(1110, 389);
            this.panel3.TabIndex = 2;
            // 
            // panel2
            // 
            this.panel2.AutoScroll = true;
            this.panel2.Controls.Add(this.label18);
            this.panel2.Controls.Add(this.txt权限时间);
            this.panel2.Controls.Add(this.label10);
            this.panel2.Controls.Add(this.label8);
            this.panel2.Controls.Add(this.txt图片删除日期);
            this.panel2.Controls.Add(this.label9);
            this.panel2.Controls.Add(this.label17);
            this.panel2.Controls.Add(this.txt相机数量设置);
            this.panel2.Controls.Add(this.label43);
            this.panel2.Controls.Add(this.txt料号名称);
            this.panel2.Controls.Add(this.button15);
            this.panel2.Controls.Add(this.button14);
            this.panel2.Controls.Add(this.button11);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel2.Location = new System.Drawing.Point(170, 624);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1110, 96);
            this.panel2.TabIndex = 3;
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            this.splitContainer1.Panel1.Controls.Add(this.splitContainer2);
            this.splitContainer1.Panel2.Controls.Add(this.splitContainer3);
            this.splitContainer1.Size = new System.Drawing.Size(1110, 389);
            this.splitContainer1.SplitterDistance = 555;
            this.splitContainer1.TabIndex = 0;
            // 
            // splitContainer2
            // 
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.Location = new System.Drawing.Point(0, 0);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Panel1.Controls.Add(this.label39);
            this.splitContainer2.Panel1.Controls.Add(this.label19);
            this.splitContainer2.Panel1.Controls.Add(this.txt相机1模板数量);
            this.splitContainer2.Panel1.Controls.Add(this.label20);
            this.splitContainer2.Panel1.Controls.Add(this.txt相机1对比度);
            this.splitContainer2.Panel1.Controls.Add(this.label44);
            this.splitContainer2.Panel1.Controls.Add(this.label21);
            this.splitContainer2.Panel1.Controls.Add(this.txt相机1匹配度);
            this.splitContainer2.Panel1.Controls.Add(this.label45);
            this.splitContainer2.Panel1.Controls.Add(this.label22);
            this.splitContainer2.Panel1.Controls.Add(this.txt相机1曝光时间);
            this.splitContainer2.Panel1.Controls.Add(this.label23);
            this.splitContainer2.Panel1.Controls.Add(this.txt相机1增益);
            this.splitContainer2.Panel2.Controls.Add(this.label41);
            this.splitContainer2.Panel2.Controls.Add(this.txt相机3模板数量);
            this.splitContainer2.Panel2.Controls.Add(this.txt相机3对比度);
            this.splitContainer2.Panel2.Controls.Add(this.txt相机3匹配度);
            this.splitContainer2.Panel2.Controls.Add(this.txt相机3曝光时间);
            this.splitContainer2.Panel2.Controls.Add(this.txt相机3增益);
            this.splitContainer2.Panel2Collapsed = true;
            this.splitContainer2.Size = new System.Drawing.Size(555, 389);
            this.splitContainer2.SplitterDistance = 555;
            this.splitContainer2.TabIndex = 0;
            // 
            // splitContainer3
            // 
            this.splitContainer3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer3.Location = new System.Drawing.Point(0, 0);
            this.splitContainer3.Name = "splitContainer3";
            this.splitContainer3.Panel1.Controls.Add(this.label40);
            this.splitContainer3.Panel1.Controls.Add(this.label24);
            this.splitContainer3.Panel1.Controls.Add(this.txt相机2模板数量);
            this.splitContainer3.Panel1.Controls.Add(this.label25);
            this.splitContainer3.Panel1.Controls.Add(this.txt相机2对比度);
            this.splitContainer3.Panel1.Controls.Add(this.label46);
            this.splitContainer3.Panel1.Controls.Add(this.label26);
            this.splitContainer3.Panel1.Controls.Add(this.txt相机2匹配度);
            this.splitContainer3.Panel1.Controls.Add(this.label47);
            this.splitContainer3.Panel1.Controls.Add(this.label27);
            this.splitContainer3.Panel1.Controls.Add(this.txt相机2曝光时间);
            this.splitContainer3.Panel1.Controls.Add(this.label28);
            this.splitContainer3.Panel1.Controls.Add(this.txt相机2增益);
            this.splitContainer3.Panel2.Controls.Add(this.label42);
            this.splitContainer3.Panel2.Controls.Add(this.txt相机4模板数量);
            this.splitContainer3.Panel2.Controls.Add(this.txt相机4对比度);
            this.splitContainer3.Panel2.Controls.Add(this.txt相机4匹配度);
            this.splitContainer3.Panel2.Controls.Add(this.txt相机4曝光时间);
            this.splitContainer3.Panel2.Controls.Add(this.txt相机4增益);
            this.splitContainer3.Panel2Collapsed = true;
            this.splitContainer3.Size = new System.Drawing.Size(551, 389);
            this.splitContainer3.SplitterDistance = 551;
            this.splitContainer3.TabIndex = 0;
            // 
            // path labels and boxes
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(35, 12);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(144, 14);
            this.label2.Text = "检测相机hdl文件路径:";
            this.txt相机1hdl.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1hdl.Location = new System.Drawing.Point(190, 8);
            this.txt相机1hdl.Name = "txt相机1hdl";
            this.txt相机1hdl.ReadOnly = true;
            this.txt相机1hdl.Size = new System.Drawing.Size(350, 23);
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label3.Location = new System.Drawing.Point(20, 45);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(159, 14);
            this.label3.Text = "检测相机hdict文件路径:";
            this.txt相机1hdict.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1hdict.Location = new System.Drawing.Point(190, 41);
            this.txt相机1hdict.Name = "txt相机1hdict";
            this.txt相机1hdict.ReadOnly = true;
            this.txt相机1hdict.Size = new System.Drawing.Size(350, 23);
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label1.Location = new System.Drawing.Point(20, 78);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(159, 14);
            this.label1.Text = "检测相机模板保存路径:";
            this.txt相机1模板保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1模板保存路径.Location = new System.Drawing.Point(190, 74);
            this.txt相机1模板保存路径.Name = "txt相机1模板保存路径";
            this.txt相机1模板保存路径.ReadOnly = true;
            this.txt相机1模板保存路径.Size = new System.Drawing.Size(350, 23);
            this.label54.AutoSize = true;
            this.label54.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label54.Location = new System.Drawing.Point(20, 111);
            this.label54.Name = "label54";
            this.label54.Size = new System.Drawing.Size(159, 14);
            this.label54.Text = "检测相机原图保存路径:";
            this.txt相机1原图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1原图保存路径.Location = new System.Drawing.Point(190, 107);
            this.txt相机1原图保存路径.Name = "txt相机1原图保存路径";
            this.txt相机1原图保存路径.ReadOnly = true;
            this.txt相机1原图保存路径.Size = new System.Drawing.Size(350, 23);
            this.label53.AutoSize = true;
            this.label53.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label53.Location = new System.Drawing.Point(12, 144);
            this.label53.Name = "label53";
            this.label53.Size = new System.Drawing.Size(167, 14);
            this.label53.Text = "检测相机OK图保存路径:";
            this.txt相机1OK图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1OK图保存路径.Location = new System.Drawing.Point(190, 140);
            this.txt相机1OK图保存路径.Name = "txt相机1OK图保存路径";
            this.txt相机1OK图保存路径.ReadOnly = true;
            this.txt相机1OK图保存路径.Size = new System.Drawing.Size(350, 23);
            this.label52.AutoSize = true;
            this.label52.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label52.Location = new System.Drawing.Point(12, 177);
            this.label52.Name = "label52";
            this.label52.Size = new System.Drawing.Size(167, 14);
            this.label52.Text = "检测相机NG图保存路径:";
            this.txt相机1NG图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机1NG图保存路径.Location = new System.Drawing.Point(190, 173);
            this.txt相机1NG图保存路径.Name = "txt相机1NG图保存路径";
            this.txt相机1NG图保存路径.ReadOnly = true;
            this.txt相机1NG图保存路径.Size = new System.Drawing.Size(350, 23);
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label5.Location = new System.Drawing.Point(590, 12);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(144, 14);
            this.label5.Text = "分类相机hdl文件路径:";
            this.txt相机2hdl.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2hdl.Location = new System.Drawing.Point(745, 8);
            this.txt相机2hdl.Name = "txt相机2hdl";
            this.txt相机2hdl.ReadOnly = true;
            this.txt相机2hdl.Size = new System.Drawing.Size(350, 23);
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label4.Location = new System.Drawing.Point(575, 45);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(159, 14);
            this.label4.Text = "分类相机hdict文件路径:";
            this.txt相机2hdict.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2hdict.Location = new System.Drawing.Point(745, 41);
            this.txt相机2hdict.Name = "txt相机2hdict";
            this.txt相机2hdict.ReadOnly = true;
            this.txt相机2hdict.Size = new System.Drawing.Size(350, 23);
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label6.Location = new System.Drawing.Point(575, 78);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(159, 14);
            this.label6.Text = "分类相机模板保存路径:";
            this.txt相机2模板保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2模板保存路径.Location = new System.Drawing.Point(745, 74);
            this.txt相机2模板保存路径.Name = "txt相机2模板保存路径";
            this.txt相机2模板保存路径.ReadOnly = true;
            this.txt相机2模板保存路径.Size = new System.Drawing.Size(350, 23);
            this.label57.AutoSize = true;
            this.label57.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label57.Location = new System.Drawing.Point(575, 111);
            this.label57.Name = "label57";
            this.label57.Size = new System.Drawing.Size(159, 14);
            this.label57.Text = "分类相机原图保存路径:";
            this.txt相机2原图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2原图保存路径.Location = new System.Drawing.Point(745, 107);
            this.txt相机2原图保存路径.Name = "txt相机2原图保存路径";
            this.txt相机2原图保存路径.ReadOnly = true;
            this.txt相机2原图保存路径.Size = new System.Drawing.Size(350, 23);
            this.label56.AutoSize = true;
            this.label56.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label56.Location = new System.Drawing.Point(567, 144);
            this.label56.Name = "label56";
            this.label56.Size = new System.Drawing.Size(167, 14);
            this.label56.Text = "分类相机OK图保存路径:";
            this.txt相机2OK图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2OK图保存路径.Location = new System.Drawing.Point(745, 140);
            this.txt相机2OK图保存路径.Name = "txt相机2OK图保存路径";
            this.txt相机2OK图保存路径.ReadOnly = true;
            this.txt相机2OK图保存路径.Size = new System.Drawing.Size(350, 23);
            this.label55.AutoSize = true;
            this.label55.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label55.Location = new System.Drawing.Point(567, 177);
            this.label55.Name = "label55";
            this.label55.Size = new System.Drawing.Size(167, 14);
            this.label55.Text = "分类相机NG图保存路径:";
            this.txt相机2NG图保存路径.Font = new System.Drawing.Font("宋体", 10.5F);
            this.txt相机2NG图保存路径.Location = new System.Drawing.Point(745, 173);
            this.txt相机2NG图保存路径.Name = "txt相机2NG图保存路径";
            this.txt相机2NG图保存路径.ReadOnly = true;
            this.txt相机2NG图保存路径.Size = new System.Drawing.Size(350, 23);
            // hidden camera 3/4 controls
            this.label11.Visible = false;
            this.label12.Visible = false;
            this.label16.Visible = false;
            this.label60.Visible = false;
            this.label59.Visible = false;
            this.label58.Visible = false;
            this.label14.Visible = false;
            this.label15.Visible = false;
            this.label13.Visible = false;
            this.label63.Visible = false;
            this.label62.Visible = false;
            this.label61.Visible = false;
            this.txt相机3hdl.Visible = false;
            this.txt相机3hdict.Visible = false;
            this.txt相机3模板保存路径.Visible = false;
            this.txt相机3原图保存路径.Visible = false;
            this.txt相机3OK图保存路径.Visible = false;
            this.txt相机3NG图保存路径.Visible = false;
            this.txt相机4hdl.Visible = false;
            this.txt相机4hdict.Visible = false;
            this.txt相机4模板保存路径.Visible = false;
            this.txt相机4原图保存路径.Visible = false;
            this.txt相机4OK图保存路径.Visible = false;
            this.txt相机4NG图保存路径.Visible = false;
            // 
            // camera parameter controls
            // 
            this.label39.AutoSize = true;
            this.label39.Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Bold);
            this.label39.Location = new System.Drawing.Point(230, 32);
            this.label39.Name = "label39";
            this.label39.Text = "检测相机";
            this.label19.AutoSize = true;
            this.label19.Location = new System.Drawing.Point(210, 88);
            this.label19.Name = "label19";
            this.label19.Text = "数量:";
            this.txt相机1模板数量.Location = new System.Drawing.Point(285, 84);
            this.txt相机1模板数量.Maximum = new decimal(new int[] { 999, 0, 0, 0 });
            this.txt相机1模板数量.Name = "txt相机1模板数量";
            this.txt相机1模板数量.Size = new System.Drawing.Size(100, 21);
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(198, 128);
            this.label20.Name = "label20";
            this.label20.Text = "对比度:";
            this.txt相机1对比度.Location = new System.Drawing.Point(285, 124);
            this.txt相机1对比度.Maximum = new decimal(new int[] { 255, 0, 0, 0 });
            this.txt相机1对比度.Name = "txt相机1对比度";
            this.txt相机1对比度.Size = new System.Drawing.Size(100, 21);
            this.label44.AutoSize = true;
            this.label44.Location = new System.Drawing.Point(408, 128);
            this.label44.Name = "label44";
            this.label44.Text = "0-255";
            this.label21.AutoSize = true;
            this.label21.Location = new System.Drawing.Point(184, 168);
            this.label21.Name = "label21";
            this.label21.Text = "匹配分数:";
            this.txt相机1匹配度.DecimalPlaces = 2;
            this.txt相机1匹配度.Increment = new decimal(new int[] { 1, 0, 0, 131072 });
            this.txt相机1匹配度.Location = new System.Drawing.Point(285, 164);
            this.txt相机1匹配度.Maximum = new decimal(new int[] { 1, 0, 0, 0 });
            this.txt相机1匹配度.Name = "txt相机1匹配度";
            this.txt相机1匹配度.Size = new System.Drawing.Size(100, 21);
            this.label45.AutoSize = true;
            this.label45.Location = new System.Drawing.Point(408, 168);
            this.label45.Name = "label45";
            this.label45.Text = "0-1";
            this.label22.AutoSize = true;
            this.label22.Location = new System.Drawing.Point(184, 208);
            this.label22.Name = "label22";
            this.label22.Text = "曝光时间:";
            this.txt相机1曝光时间.Location = new System.Drawing.Point(285, 204);
            this.txt相机1曝光时间.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
            this.txt相机1曝光时间.Name = "txt相机1曝光时间";
            this.txt相机1曝光时间.Size = new System.Drawing.Size(100, 21);
            this.label23.AutoSize = true;
            this.label23.Location = new System.Drawing.Point(210, 248);
            this.label23.Name = "label23";
            this.label23.Text = "增益:";
            this.txt相机1增益.Location = new System.Drawing.Point(285, 244);
            this.txt相机1增益.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
            this.txt相机1增益.Name = "txt相机1增益";
            this.txt相机1增益.Size = new System.Drawing.Size(100, 21);
            this.label40.AutoSize = true;
            this.label40.Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Bold);
            this.label40.Location = new System.Drawing.Point(230, 32);
            this.label40.Name = "label40";
            this.label40.Text = "分类相机";
            this.label24.AutoSize = true;
            this.label24.Location = new System.Drawing.Point(210, 88);
            this.label24.Name = "label24";
            this.label24.Text = "数量:";
            this.txt相机2模板数量.Location = new System.Drawing.Point(285, 84);
            this.txt相机2模板数量.Maximum = new decimal(new int[] { 999, 0, 0, 0 });
            this.txt相机2模板数量.Name = "txt相机2模板数量";
            this.txt相机2模板数量.Size = new System.Drawing.Size(100, 21);
            this.label25.AutoSize = true;
            this.label25.Location = new System.Drawing.Point(198, 128);
            this.label25.Name = "label25";
            this.label25.Text = "对比度:";
            this.txt相机2对比度.Location = new System.Drawing.Point(285, 124);
            this.txt相机2对比度.Maximum = new decimal(new int[] { 255, 0, 0, 0 });
            this.txt相机2对比度.Name = "txt相机2对比度";
            this.txt相机2对比度.Size = new System.Drawing.Size(100, 21);
            this.label46.AutoSize = true;
            this.label46.Location = new System.Drawing.Point(408, 128);
            this.label46.Name = "label46";
            this.label46.Text = "0-255";
            this.label26.AutoSize = true;
            this.label26.Location = new System.Drawing.Point(184, 168);
            this.label26.Name = "label26";
            this.label26.Text = "匹配分数:";
            this.txt相机2匹配度.DecimalPlaces = 2;
            this.txt相机2匹配度.Increment = new decimal(new int[] { 1, 0, 0, 131072 });
            this.txt相机2匹配度.Location = new System.Drawing.Point(285, 164);
            this.txt相机2匹配度.Maximum = new decimal(new int[] { 1, 0, 0, 0 });
            this.txt相机2匹配度.Name = "txt相机2匹配度";
            this.txt相机2匹配度.Size = new System.Drawing.Size(100, 21);
            this.label47.AutoSize = true;
            this.label47.Location = new System.Drawing.Point(408, 168);
            this.label47.Name = "label47";
            this.label47.Text = "0-1";
            this.label27.AutoSize = true;
            this.label27.Location = new System.Drawing.Point(184, 208);
            this.label27.Name = "label27";
            this.label27.Text = "曝光时间:";
            this.txt相机2曝光时间.Location = new System.Drawing.Point(285, 204);
            this.txt相机2曝光时间.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
            this.txt相机2曝光时间.Name = "txt相机2曝光时间";
            this.txt相机2曝光时间.Size = new System.Drawing.Size(100, 21);
            this.label28.AutoSize = true;
            this.label28.Location = new System.Drawing.Point(210, 248);
            this.label28.Name = "label28";
            this.label28.Text = "增益:";
            this.txt相机2增益.Location = new System.Drawing.Point(285, 244);
            this.txt相机2增益.Maximum = new decimal(new int[] { 1000, 0, 0, 0 });
            this.txt相机2增益.Name = "txt相机2增益";
            this.txt相机2增益.Size = new System.Drawing.Size(100, 21);
            this.label41.Visible = false;
            this.label42.Visible = false;
            // Hidden numeric controls still exist for compatibility.
            this.txt相机3模板数量.Visible = false;
            this.txt相机3对比度.Visible = false;
            this.txt相机3匹配度.Visible = false;
            this.txt相机3曝光时间.Visible = false;
            this.txt相机3增益.Visible = false;
            this.txt相机4模板数量.Visible = false;
            this.txt相机4对比度.Visible = false;
            this.txt相机4匹配度.Visible = false;
            this.txt相机4曝光时间.Visible = false;
            this.txt相机4增益.Visible = false;
            this.label29.Visible = false;
            this.label30.Visible = false;
            this.label31.Visible = false;
            this.label32.Visible = false;
            this.label33.Visible = false;
            this.label34.Visible = false;
            this.label35.Visible = false;
            this.label36.Visible = false;
            this.label37.Visible = false;
            this.label38.Visible = false;
            this.label48.Visible = false;
            this.label49.Visible = false;
            this.label50.Visible = false;
            this.label51.Visible = false;
            // 
            // bottom controls
            // 
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label18.Location = new System.Drawing.Point(20, 18);
            this.label18.Name = "label18";
            this.label18.Text = "界面无操作时管理员权限退出时间:";
            this.txt权限时间.Location = new System.Drawing.Point(300, 14);
            this.txt权限时间.Name = "txt权限时间";
            this.txt权限时间.ReadOnly = true;
            this.txt权限时间.Size = new System.Drawing.Size(100, 23);
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label10.Location = new System.Drawing.Point(420, 18);
            this.label10.Name = "label10";
            this.label10.Text = "分";
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label8.Location = new System.Drawing.Point(83, 58);
            this.label8.Name = "label8";
            this.label8.Text = "图片自动删除时间:";
            this.txt图片删除日期.Location = new System.Drawing.Point(300, 54);
            this.txt图片删除日期.Name = "txt图片删除日期";
            this.txt图片删除日期.ReadOnly = true;
            this.txt图片删除日期.Size = new System.Drawing.Size(100, 23);
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label9.Location = new System.Drawing.Point(420, 58);
            this.label9.Name = "label9";
            this.label9.Text = "天";
            this.label17.AutoSize = true;
            this.label17.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label17.Location = new System.Drawing.Point(500, 18);
            this.label17.Name = "label17";
            this.label17.Text = "相机数量:";
            this.txt相机数量设置.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txt相机数量设置.Items.AddRange(new object[] { "1", "2" });
            this.txt相机数量设置.Location = new System.Drawing.Point(585, 14);
            this.txt相机数量设置.Name = "txt相机数量设置";
            this.txt相机数量设置.Size = new System.Drawing.Size(80, 20);
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label7.Location = new System.Drawing.Point(670, 18);
            this.label7.Name = "label7";
            this.label7.Text = "个";
            this.label43.AutoSize = true;
            this.label43.Font = new System.Drawing.Font("宋体", 10.5F, System.Drawing.FontStyle.Bold);
            this.label43.Location = new System.Drawing.Point(500, 58);
            this.label43.Name = "label43";
            this.label43.Text = "料号名称:";
            this.txt料号名称.Location = new System.Drawing.Point(585, 54);
            this.txt料号名称.Name = "txt料号名称";
            this.txt料号名称.Size = new System.Drawing.Size(180, 20);
            this.button15.Location = new System.Drawing.Point(800, 12);
            this.button15.Name = "button15";
            this.button15.Size = new System.Drawing.Size(75, 30);
            this.button15.Text = "增加";
            this.button15.UseVisualStyleBackColor = true;
            this.button15.Click += new System.EventHandler(this.button15_Click);
            this.button14.Location = new System.Drawing.Point(890, 12);
            this.button14.Name = "button14";
            this.button14.Size = new System.Drawing.Size(75, 30);
            this.button14.Text = "删除";
            this.button14.UseVisualStyleBackColor = true;
            this.button14.Click += new System.EventHandler(this.button14_Click);
            this.button11.Location = new System.Drawing.Point(980, 12);
            this.button11.Name = "button11";
            this.button11.Size = new System.Drawing.Size(75, 30);
            this.button11.Text = "保存";
            this.button11.UseVisualStyleBackColor = true;
            this.button11.Click += new System.EventHandler(this.button11_Click);
            // 
            // 料号添加
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1280, 720);
            this.ControlBox = false;
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.listBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "料号添加";
            this.Text = "料号添加";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel1.PerformLayout();
            this.splitContainer2.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.splitContainer3.Panel1.ResumeLayout(false);
            this.splitContainer3.Panel1.PerformLayout();
            this.splitContainer3.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).EndInit();
            this.splitContainer3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1模板数量)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1对比度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1匹配度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1曝光时间)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机1增益)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2模板数量)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2对比度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2匹配度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2曝光时间)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机2增益)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3模板数量)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3对比度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3匹配度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3曝光时间)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机3增益)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4模板数量)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4对比度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4匹配度)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4曝光时间)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txt相机4增益)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.TextBox txt相机1hdict;
        private System.Windows.Forms.TextBox txt相机1hdl;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txt相机2hdl;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txt相机2hdict;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txt相机3hdict;
        private System.Windows.Forms.TextBox txt相机3hdl;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox txt相机4hdict;
        private System.Windows.Forms.TextBox txt相机4hdl;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox txt相机1模板保存路径;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txt相机2模板保存路径;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txt相机4模板保存路径;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txt相机3模板保存路径;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.ComboBox txt相机数量设置;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.TextBox txt图片删除日期;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txt权限时间;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.NumericUpDown txt相机1匹配度;
        private System.Windows.Forms.NumericUpDown txt相机1对比度;
        private System.Windows.Forms.NumericUpDown txt相机1模板数量;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.SplitContainer splitContainer2;
        private System.Windows.Forms.SplitContainer splitContainer3;
        private System.Windows.Forms.Label label43;
        private System.Windows.Forms.Button button15;
        private System.Windows.Forms.Button button14;
        private System.Windows.Forms.Button button11;
        private System.Windows.Forms.Label label39;
        private System.Windows.Forms.Label label41;
        private System.Windows.Forms.NumericUpDown txt相机3匹配度;
        private System.Windows.Forms.NumericUpDown txt相机3对比度;
        private System.Windows.Forms.Label label29;
        private System.Windows.Forms.Label label30;
        private System.Windows.Forms.NumericUpDown txt相机3模板数量;
        private System.Windows.Forms.Label label31;
        private System.Windows.Forms.Label label32;
        private System.Windows.Forms.Label label33;
        private System.Windows.Forms.Label label40;
        private System.Windows.Forms.NumericUpDown txt相机2匹配度;
        private System.Windows.Forms.NumericUpDown txt相机2对比度;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.NumericUpDown txt相机2模板数量;
        private System.Windows.Forms.Label label26;
        private System.Windows.Forms.Label label27;
        private System.Windows.Forms.Label label28;
        private System.Windows.Forms.Label label42;
        private System.Windows.Forms.NumericUpDown txt相机4匹配度;
        private System.Windows.Forms.NumericUpDown txt相机4对比度;
        private System.Windows.Forms.Label label34;
        private System.Windows.Forms.Label label35;
        private System.Windows.Forms.NumericUpDown txt相机4模板数量;
        private System.Windows.Forms.Label label36;
        private System.Windows.Forms.Label label37;
        private System.Windows.Forms.Label label38;
        private System.Windows.Forms.Label label44;
        private System.Windows.Forms.Label label45;
        private System.Windows.Forms.NumericUpDown txt相机1增益;
        private System.Windows.Forms.NumericUpDown txt相机1曝光时间;
        private System.Windows.Forms.Label label48;
        private System.Windows.Forms.Label label49;
        private System.Windows.Forms.NumericUpDown txt相机3增益;
        private System.Windows.Forms.NumericUpDown txt相机3曝光时间;
        private System.Windows.Forms.Label label46;
        private System.Windows.Forms.Label label47;
        private System.Windows.Forms.NumericUpDown txt相机2增益;
        private System.Windows.Forms.NumericUpDown txt相机2曝光时间;
        private System.Windows.Forms.Label label50;
        private System.Windows.Forms.Label label51;
        private System.Windows.Forms.NumericUpDown txt相机4增益;
        private System.Windows.Forms.NumericUpDown txt相机4曝光时间;
        private System.Windows.Forms.ComboBox txt料号名称;
        private System.Windows.Forms.TextBox txt相机4NG图保存路径;
        private System.Windows.Forms.Label label61;
        private System.Windows.Forms.TextBox txt相机4OK图保存路径;
        private System.Windows.Forms.Label label62;
        private System.Windows.Forms.TextBox txt相机4原图保存路径;
        private System.Windows.Forms.Label label63;
        private System.Windows.Forms.TextBox txt相机3NG图保存路径;
        private System.Windows.Forms.Label label58;
        private System.Windows.Forms.TextBox txt相机3OK图保存路径;
        private System.Windows.Forms.Label label59;
        private System.Windows.Forms.TextBox txt相机3原图保存路径;
        private System.Windows.Forms.Label label60;
        private System.Windows.Forms.TextBox txt相机2NG图保存路径;
        private System.Windows.Forms.Label label55;
        private System.Windows.Forms.TextBox txt相机2OK图保存路径;
        private System.Windows.Forms.Label label56;
        private System.Windows.Forms.TextBox txt相机2原图保存路径;
        private System.Windows.Forms.Label label57;
        private System.Windows.Forms.TextBox txt相机1NG图保存路径;
        private System.Windows.Forms.Label label52;
        private System.Windows.Forms.TextBox txt相机1OK图保存路径;
        private System.Windows.Forms.Label label53;
        private System.Windows.Forms.TextBox txt相机1原图保存路径;
        private System.Windows.Forms.Label label54;
    }
}
